# Generated by Django 3.2.3 on 2021-05-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210518_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='club',
        ),
    ]
