# Generated by Django 3.2.3 on 2021-05-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.club'),
        ),
    ]
