# Generated by Django 3.2.3 on 2021-05-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_request_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='club',
        ),
        migrations.AddField(
            model_name='item',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.club'),
        ),
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
