# Generated by Django 3.2.3 on 2021-05-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_club', to='users.club'),
        ),
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='users.item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_club', to='users.club'),
        ),
    ]
