# Generated by Django 3.2.3 on 2021-05-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210526_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_of_club', to='users.club'),
        ),
        migrations.AlterField(
            model_name='request',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_of_user', to='users.userprofile'),
        ),
    ]
