# Generated by Django 3.2.3 on 2021-05-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210526_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Convenor', 'Convenor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_of_item', to='users.item'),
        ),
    ]
