# Generated by Django 3.2.3 on 2021-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210528_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Convenor', 'Convenor'), ('Admin', 'Admin')], max_length=200, null=True),
        ),
    ]
