# Generated by Django 3.2.3 on 2021-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('None', 'None'), ('Member', 'Member'), ('Convenor', 'Convenor')], default='None', max_length=200, null=True),
        ),
    ]
